project:
  type: book
  output-dir: _book

book:
  title: "The Complete Idiot's Guide to Ending War and Disease"
  author: "Mike P. Sinn"
  date: "today"
  chapters:
    - index.qmd

format:
  html:
    theme: cosmo
    echo: false
  pdf:
    documentclass: scrreprt
    echo: false
