project:
  type: book
  output-dir: _book
  execute-dir: project

book:
  title: "The Complete Idiot's Guide to Ending War and Disease"
  author: "Mike P. Sinn"
  date: "today"
  chapters:
    - index.qmd
    - part: "The Problem"
      chapters:
        - brain/book/problem/the-evolutionary-trap.md
        - brain/book/problem/cost-of-war.md
        - brain/book/problem/cost-of-disease.md
    - part: "The Solution"
      chapters:
        - brain/book/solution/1-percent-treaty.md
        - brain/book/solution/dih.qmd
        - brain/book/solution/dfda.md
        - brain/book/solution/wishocracy.md
    - part: "The Proof"
      chapters:
        - brain/book/proof/historical-precedents.md
        - brain/book/proof/body-as-repairable-machine.md

execute:
  # Relaunch kernel for each render
  cache: false
  freeze: auto

# Tell Quarto to use the project's virtual environment
jupyter: dih-project-kernel

format:
  html:
    theme: 
      - brite
      - neobrutalist.scss
    # theme: lux also nice (https://bootswatch.com/brite/)
    echo: false
    number-sections: false
  pdf:
    documentclass: scrreprt
    echo: false
