project:
  type: book
  output-dir: _book
  execute-dir: project

book:
  title: "The Complete Idiot's Guide to Ending War and Disease"
  author: "Mike P. Sinn"
  date: "today"
  chapters:
    - index.qmd
    - brain/book/solution/dih.qmd

execute:
  # Relaunch kernel for each render
  cache: false
  freeze: auto

# Tell Quarto to use the project's virtual environment
jupyter: dih-project-kernel

format:
  html:
    theme: 
      - brite
      - neobrutalist.scss
    # theme: lux also nice (https://bootswatch.com/brite/)
    echo: false
    number-sections: false
  pdf:
    documentclass: scrreprt
    echo: false
